project: 
  type: website
  output-dir: docs

website:
  title: "Murtaza Yaqubi's Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Data Exercise"
            file: data-exercise/data-exercise.qmd
          - text: "Data Analysis Exercise"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "presentation-exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "fitting-exercise"
            file: fitting-exercise/fitting-exercise.qmd
          - text: "ml-models-exercise"
            file: ml-models-exercise/ml-models-exercise.qmd
          - text: "tidytuesday-exercise"
            file: tidytuesday-exercise/tidytuesday-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/Murtaza-Yaqubi/MurtazaYaqubi-MADA-portfolio       
format:
  html:
    theme: sandstone
    highlight: zenburn
    css: styles.css
    toc: FALSE