<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R Coding Exercise – Murtaza Yaqubi’s Data Analysis Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-df479d6c4d77d0e0dfbcb5361179d7fd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Murtaza Yaqubi’s Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/data-exercise.html">
 <span class="dropdown-text">Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdcdata-exercise/cdcdata-exercise.html">
 <span class="dropdown-text">Data Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html">
 <span class="dropdown-text">presentation-exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../fitting-exercise/fitting-exercise.html">
 <span class="dropdown-text">fitting-exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../ml-models-exercise/ml-models-exercise.html">
 <span class="dropdown-text">ml-models-exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidytuesday-exercise/tidytuesday-exercise.html">
 <span class="dropdown-text">tidytuesday-exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Murtaza-Yaqubi/MurtazaYaqubi-MADA-portfolio"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R Coding Exercise</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="loading-and-checking-data" class="level3">
<h3 class="anchored" data-anchor-id="loading-and-checking-data">Loading and checking data:</h3>
<p>First we begin by installing necessary packages for this analysis if we haven’t already. Once the package installs, we need to load the package using library function. We need to load the packages before use, every time we open R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"dslabs"</span>, <span class="at">repos =</span> <span class="st">"https://cran.rstudio.com/"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Installing package into 'C:/Users/shaun/AppData/Local/R/win-library/4.4'
(as 'lib' is unspecified)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>package 'dslabs' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
    C:\Users\shaun\AppData\Local\Temp\Rtmp8eDCFA\downloaded_packages</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dslabs"</span>)      <span class="co">#load the package.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dslabs' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)   <span class="co">#This is a good package for data processing tasks and since I have it installed, I only had to load it. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.4     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)       <span class="co">#use to generate plots. </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)         <span class="co">#load this package if you want to use %&gt;%</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we are going to look into help file for gapminder data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(<span class="st">"gapminder"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>starting httpd help server ... done</code></pre>
</div>
</div>
<p>We use the following function inorder to get an overview of the data structure.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(gapminder) <span class="co">#get an over view of data structure.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   10545 obs. of  9 variables:
 $ country         : Factor w/ 185 levels "Albania","Algeria",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ year            : int  1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 ...
 $ infant_mortality: num  115.4 148.2 208 NA 59.9 ...
 $ life_expectancy : num  62.9 47.5 36 63 65.4 ...
 $ fertility       : num  6.19 7.65 7.32 4.43 3.11 4.55 4.82 3.45 2.7 5.57 ...
 $ population      : num  1636054 11124892 5270844 54681 20619075 ...
 $ gdp             : num  NA 1.38e+10 NA NA 1.08e+11 ...
 $ continent       : Factor w/ 5 levels "Africa","Americas",..: 4 1 1 2 2 3 2 5 4 3 ...
 $ region          : Factor w/ 22 levels "Australia and New Zealand",..: 19 11 10 2 15 21 2 1 22 21 ...</code></pre>
</div>
</div>
<p>We are now going to look into the summary of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gapminder)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                country           year      infant_mortality life_expectancy
 Albania            :   57   Min.   :1960   Min.   :  1.50   Min.   :13.20  
 Algeria            :   57   1st Qu.:1974   1st Qu.: 16.00   1st Qu.:57.50  
 Angola             :   57   Median :1988   Median : 41.50   Median :67.54  
 Antigua and Barbuda:   57   Mean   :1988   Mean   : 55.31   Mean   :64.81  
 Argentina          :   57   3rd Qu.:2002   3rd Qu.: 85.10   3rd Qu.:73.00  
 Armenia            :   57   Max.   :2016   Max.   :276.90   Max.   :83.90  
 (Other)            :10203                  NA's   :1453                    
   fertility       population             gdp               continent   
 Min.   :0.840   Min.   :3.124e+04   Min.   :4.040e+07   Africa  :2907  
 1st Qu.:2.200   1st Qu.:1.333e+06   1st Qu.:1.846e+09   Americas:2052  
 Median :3.750   Median :5.009e+06   Median :7.794e+09   Asia    :2679  
 Mean   :4.084   Mean   :2.701e+07   Mean   :1.480e+11   Europe  :2223  
 3rd Qu.:6.000   3rd Qu.:1.523e+07   3rd Qu.:5.540e+10   Oceania : 684  
 Max.   :9.220   Max.   :1.376e+09   Max.   :1.174e+13                  
 NA's   :187     NA's   :185         NA's   :2972                       
             region    
 Western Asia   :1026  
 Eastern Africa : 912  
 Western Africa : 912  
 Caribbean      : 741  
 South America  : 684  
 Southern Europe: 684  
 (Other)        :5586  </code></pre>
</div>
</div>
<p>Let us determine the type of object “gapminder” is.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(gapminder)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
</section>
<section id="processing-data" class="level3">
<h3 class="anchored" data-anchor-id="processing-data">Processing Data:</h3>
<p>For this part of data prcessing we want to focus on Africa only so we will create an objest called africadata that holds all the data for Africa.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>africadata <span class="ot">&lt;-</span> <span class="fu">filter</span>(gapminder, continent <span class="sc">==</span> <span class="st">"Africa"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s check africadata.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(africadata, <span class="at">n =</span> <span class="dv">100</span>) <span class="co">#view the first 100 rows of the dataset.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     country year infant_mortality life_expectancy fertility
1                    Algeria 1960            148.2           47.50      7.65
2                     Angola 1960            208.0           35.98      7.32
3                      Benin 1960            186.9           38.29      6.28
4                   Botswana 1960            115.5           50.34      6.62
5               Burkina Faso 1960            161.3           35.21      6.29
6                    Burundi 1960            145.1           40.58      6.95
7                   Cameroon 1960            166.9           43.46      5.65
8                 Cape Verde 1960               NA           50.12      6.89
9   Central African Republic 1960            165.5           37.43      5.84
10                      Chad 1960               NA           40.95      6.25
11                   Comoros 1960            200.0           44.04      6.79
12          Congo, Dem. Rep. 1960            174.0           43.90      6.00
13               Congo, Rep. 1960            110.6           48.25      5.88
14             Cote d'Ivoire 1960            208.4           38.00      7.35
15                  Djibouti 1960               NA           45.77      6.46
16                     Egypt 1960            209.6           48.31      6.63
17         Equatorial Guinea 1960               NA           37.69      5.51
18                   Eritrea 1960               NA           39.03      6.90
19                  Ethiopia 1960            162.0           37.72      6.88
20                     Gabon 1960               NA           38.83      4.38
21                    Gambia 1960            148.4           35.70      5.57
22                     Ghana 1960            125.1           46.34      6.75
23                    Guinea 1960               NA           35.71      6.10
24             Guinea-Bissau 1960               NA           43.14      5.83
25                     Kenya 1960            118.6           47.42      7.95
26                   Lesotho 1960            143.3           47.02      5.84
27                   Liberia 1960            212.0           35.24      6.41
28                     Libya 1960            164.5           44.59      7.54
29                Madagascar 1960            112.0           41.96      7.30
30                    Malawi 1960            218.2           38.51      6.91
31                      Mali 1960            237.4           29.61      6.70
32                Mauritania 1960            135.0           43.91      6.78
33                 Mauritius 1960             67.8           58.74      6.17
34                   Morocco 1960            145.0           49.64      7.07
35                Mozambique 1960            183.0           38.17      6.60
36                   Namibia 1960            102.0           47.07      6.15
37                     Niger 1960               NA           36.82      7.05
38                   Nigeria 1960            165.0           40.39      6.35
39                    Rwanda 1960            127.9           43.07      8.19
40                   Senegal 1960            126.3           38.46      6.95
41                Seychelles 1960             73.6           60.42      5.27
42              Sierra Leone 1960            223.6           36.07      6.03
43              South Africa 1960               NA           49.01      6.17
44                     Sudan 1960            107.4           49.54      6.69
45                 Swaziland 1960            141.7           44.78      6.72
46                  Tanzania 1960            144.3           45.57      6.81
47                      Togo 1960            162.4           41.06      6.52
48                   Tunisia 1960            173.4           43.20      7.04
49                    Uganda 1960            132.3           45.27      7.00
50                    Zambia 1960            123.2           48.34      7.02
51                  Zimbabwe 1960             92.6           53.11      7.16
52                   Algeria 1961            148.1           48.02      7.65
53                    Angola 1961               NA           36.53      7.35
54                     Benin 1961            183.9           38.80      6.34
55                  Botswana 1961            112.2           50.70      6.63
56              Burkina Faso 1961            159.4           35.72      6.32
57                   Burundi 1961            144.8           40.85      7.00
58                  Cameroon 1961            163.3           44.00      5.71
59                Cape Verde 1961               NA           50.27      6.92
60  Central African Republic 1961            162.9           37.89      5.87
61                      Chad 1961               NA           41.35      6.27
62                   Comoros 1961               NA           44.47      6.85
63          Congo, Dem. Rep. 1961               NA           44.25      6.02
64               Congo, Rep. 1961            108.4           48.88      5.92
65             Cote d'Ivoire 1961            203.0           38.74      7.43
66                  Djibouti 1961               NA           46.28      6.49
67                     Egypt 1961            202.7           48.89      6.61
68         Equatorial Guinea 1961               NA           38.04      5.52
69                   Eritrea 1961               NA           39.35      6.87
70                  Ethiopia 1961               NA           38.35      6.88
71                     Gabon 1961               NA           39.15      4.46
72                    Gambia 1961            146.1           36.16      5.62
73                     Ghana 1961            123.8           46.80      6.79
74                    Guinea 1961            210.5           35.95      6.11
75             Guinea-Bissau 1961               NA           43.39      5.77
76                     Kenya 1961            114.0           48.13      8.00
77                   Lesotho 1961            142.3           47.54      5.83
78                   Liberia 1961            212.1           35.54      6.43
79                     Libya 1961            156.1           46.28      7.57
80                Madagascar 1961               NA           42.54      7.30
81                    Malawi 1961            216.4           38.76      6.95
82                      Mali 1961            231.5           29.83      6.73
83                Mauritania 1961            131.9           44.62      6.79
84                 Mauritius 1961             66.3           59.75      6.18
85                   Morocco 1961            142.7           50.11      7.11
86                Mozambique 1961               NA           38.79      6.60
87                   Namibia 1961               NA           47.70      6.17
88                     Niger 1961               NA           36.97      7.08
89                   Nigeria 1961               NA           41.00      6.35
90                    Rwanda 1961            125.3           43.41      8.19
91                   Senegal 1961            126.0           38.63      6.99
92                Seychelles 1961             72.3           61.03      5.40
93              Sierra Leone 1961            220.5           36.57      6.09
94              South Africa 1961               NA           49.40      6.14
95                     Sudan 1961            105.7           50.04      6.71
96                 Swaziland 1961            140.1           45.10      6.73
97                  Tanzania 1961            143.0           45.91      6.81
98                      Togo 1961            159.4           41.74      6.57
99                   Tunisia 1961            187.5           43.89      7.09
100                   Uganda 1961            129.6           45.91      7.02
    population         gdp continent          region
1     11124892 13828152297    Africa Northern Africa
2      5270844          NA    Africa   Middle Africa
3      2431620   621797131    Africa  Western Africa
4       524029   124460933    Africa Southern Africa
5      4829291   596612183    Africa  Western Africa
6      2786740   341126765    Africa  Eastern Africa
7      5361367  2537944080    Africa   Middle Africa
8       202316          NA    Africa  Western Africa
9      1503501   534982718    Africa   Middle Africa
10     3002596   750173439    Africa   Middle Africa
11      188732          NA    Africa  Eastern Africa
12    15248246  4992962083    Africa   Middle Africa
13     1013581   626127041    Africa   Middle Africa
14     3474724  2003623491    Africa  Western Africa
15       83636          NA    Africa  Eastern Africa
16    27072397 12008501551    Africa Northern Africa
17      252115          NA    Africa   Middle Africa
18     1407631          NA    Africa  Eastern Africa
19    22151218          NA    Africa  Eastern Africa
20      499189   887289809    Africa   Middle Africa
21      367929          NA    Africa  Western Africa
22     6652285  1902005320    Africa  Western Africa
23     3577413          NA    Africa  Western Africa
24      616407          NA    Africa  Western Africa
25     8105440  2116484537    Africa  Eastern Africa
26      851412   112602724    Africa Southern Africa
27     1120314   678395865    Africa  Western Africa
28     1434576          NA    Africa Northern Africa
29     5099371  2087989940    Africa  Eastern Africa
30     3618604   347712093    Africa  Eastern Africa
31     5263730          NA    Africa  Western Africa
32      858170   319353267    Africa  Western Africa
33      660023          NA    Africa  Eastern Africa
34    12328534  7532416437    Africa Northern Africa
35     7493278          NA    Africa  Eastern Africa
36      602545          NA    Africa Southern Africa
37     3395212  1020197091    Africa  Western Africa
38    45211614 12836410903    Africa  Western Africa
39     2933424   623378345    Africa  Eastern Africa
40     3177560  1870217818    Africa  Western Africa
41       41538    48981400    Africa  Eastern Africa
42     2181701   488526149    Africa  Western Africa
43    17396367 38336071006    Africa Southern Africa
44     7527450  3292300613    Africa Northern Africa
45      349233          NA    Africa Southern Africa
46    10074490          NA    Africa  Eastern Africa
47     1580513   278575742    Africa  Western Africa
48     4176266          NA    Africa Northern Africa
49     6788211          NA    Africa  Eastern Africa
50     3049586  1666817402    Africa  Eastern Africa
51     3752390  1459732283    Africa  Eastern Africa
52    11404859 11946771141    Africa Northern Africa
53     5367287          NA    Africa   Middle Africa
54     2466002   641329523    Africa  Western Africa
55      536576   132351054    Africa Southern Africa
56     4894578   620738750    Africa  Western Africa
57     2840375   294235019    Africa  Eastern Africa
58     5474509  2785779139    Africa   Middle Africa
59      205958          NA    Africa  Western Africa
60     1529229   561479896    Africa   Middle Africa
61     3061423   760658941    Africa   Middle Africa
62      191828          NA    Africa  Eastern Africa
63    15637715  4451156989    Africa   Middle Africa
64     1039966   678538008    Africa   Middle Africa
65     3602075  2202622974    Africa  Western Africa
66       88499          NA    Africa  Eastern Africa
67    27810001 12536920098    Africa Northern Africa
68      255100          NA    Africa   Middle Africa
69     1441297          NA    Africa  Eastern Africa
70    22671131          NA    Africa  Eastern Africa
71      504174  1018309175    Africa   Middle Africa
72      376736          NA    Africa  Western Africa
73     6866545  1965121691    Africa  Western Africa
74     3633778          NA    Africa  Western Africa
75      623413          NA    Africa  Western Africa
76     8361442  1949773813    Africa  Eastern Africa
77      866253   114702544    Africa Southern Africa
78     1144896   694948647    Africa  Western Africa
79     1483856          NA    Africa Northern Africa
80     5223621  2130711083    Africa  Eastern Africa
81     3700032   374275949    Africa  Eastern Africa
82     5322267          NA    Africa  Western Africa
83      883223   368948552    Africa  Western Africa
84      679045          NA    Africa  Eastern Africa
85    12713043  7349737688    Africa Northern Africa
86     7643290          NA    Africa  Eastern Africa
87      617282          NA    Africa Southern Africa
88     3493636  1066579260    Africa  Western Africa
89    46144154 12861030560    Africa  Western Africa
90     2996091   597789678    Africa  Eastern Africa
91     3265558  1931233186    Africa  Western Africa
92       42402    46589993    Africa  Eastern Africa
93     2210169   497363800    Africa  Western Africa
94    17850045 39810250010    Africa Southern Africa
95     7749884  3322278876    Africa Northern Africa
96      357522          NA    Africa Southern Africa
97    10373380          NA    Africa  Eastern Africa
98     1597528   312474882    Africa  Western Africa
99     4235936  2957595859    Africa Northern Africa
100    7006629          NA    Africa  Eastern Africa</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(africadata) <span class="co">#get an overview the data structure.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2907 obs. of  9 variables:
 $ country         : Factor w/ 185 levels "Albania","Algeria",..: 2 3 18 22 26 27 29 31 32 33 ...
 $ year            : int  1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 ...
 $ infant_mortality: num  148 208 187 116 161 ...
 $ life_expectancy : num  47.5 36 38.3 50.3 35.2 ...
 $ fertility       : num  7.65 7.32 6.28 6.62 6.29 6.95 5.65 6.89 5.84 6.25 ...
 $ population      : num  11124892 5270844 2431620 524029 4829291 ...
 $ gdp             : num  1.38e+10 NA 6.22e+08 1.24e+08 5.97e+08 ...
 $ continent       : Factor w/ 5 levels "Africa","Americas",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ region          : Factor w/ 22 levels "Australia and New Zealand",..: 11 10 20 17 20 5 10 20 10 10 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(africadata) <span class="co">#get a summary of data.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         country          year      infant_mortality life_expectancy
 Algeria     :  57   Min.   :1960   Min.   : 11.40   Min.   :13.20  
 Angola      :  57   1st Qu.:1974   1st Qu.: 62.20   1st Qu.:48.23  
 Benin       :  57   Median :1988   Median : 93.40   Median :53.98  
 Botswana    :  57   Mean   :1988   Mean   : 95.12   Mean   :54.38  
 Burkina Faso:  57   3rd Qu.:2002   3rd Qu.:124.70   3rd Qu.:60.10  
 Burundi     :  57   Max.   :2016   Max.   :237.40   Max.   :77.60  
 (Other)     :2565                  NA's   :226                     
   fertility       population             gdp               continent   
 Min.   :1.500   Min.   :    41538   Min.   :4.659e+07   Africa  :2907  
 1st Qu.:5.160   1st Qu.:  1605232   1st Qu.:8.373e+08   Americas:   0  
 Median :6.160   Median :  5570982   Median :2.448e+09   Asia    :   0  
 Mean   :5.851   Mean   : 12235961   Mean   :9.346e+09   Europe  :   0  
 3rd Qu.:6.860   3rd Qu.: 13888152   3rd Qu.:6.552e+09   Oceania :   0  
 Max.   :8.450   Max.   :182201962   Max.   :1.935e+11                  
 NA's   :51      NA's   :51          NA's   :637                        
                       region   
 Eastern Africa           :912  
 Western Africa           :912  
 Middle Africa            :456  
 Northern Africa          :342  
 Southern Africa          :285  
 Australia and New Zealand:  0  
 (Other)                  :  0  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(africadata) <span class="co">#check the dimensions of data.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2907    9</code></pre>
</div>
</div>
<p>I want to create a new dataset called inf.mort_lf.exp that only includes two columns infant_mortality and life_expectancy, using africadata.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>inf.mort_lf.exp <span class="ot">&lt;-</span> africadata <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"infant_mortality"</span>, <span class="st">"life_expectancy"</span>) <span class="co">#create a new dataset from africadata that only contains two columns namely, infant_mortality and life_expectancy. </span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(inf.mort_lf.exp) <span class="co">#get an overview of the data structure.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2907 obs. of  2 variables:
 $ infant_mortality: num  148 208 187 116 161 ...
 $ life_expectancy : num  47.5 36 38.3 50.3 35.2 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(inf.mort_lf.exp) <span class="co">#get a summary of the data.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> infant_mortality life_expectancy
 Min.   : 11.40   Min.   :13.20  
 1st Qu.: 62.20   1st Qu.:48.23  
 Median : 93.40   Median :53.98  
 Mean   : 95.12   Mean   :54.38  
 3rd Qu.:124.70   3rd Qu.:60.10  
 Max.   :237.40   Max.   :77.60  
 NA's   :226                     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(inf.mort_lf.exp) <span class="co">#check number of row/observations. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2907</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(inf.mort_lf.exp) <span class="co">#check the dimensions of the data.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2907    2</code></pre>
</div>
</div>
<p>I want to create another dataset called pop_lf.exp that only includes population and life_expectancy from africadat.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>pop_lf.exp <span class="ot">&lt;-</span> africadata <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"population"</span>, <span class="st">"life_expectancy"</span>) <span class="co">#create a new dataset from africadata with only two columns namely, population and life_expectancy. </span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(pop_lf.exp) <span class="co">#get an overview of the data structure.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2907 obs. of  2 variables:
 $ population     : num  11124892 5270844 2431620 524029 4829291 ...
 $ life_expectancy: num  47.5 36 38.3 50.3 35.2 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pop_lf.exp) <span class="co">#get a summary of the data.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   population        life_expectancy
 Min.   :    41538   Min.   :13.20  
 1st Qu.:  1605232   1st Qu.:48.23  
 Median :  5570982   Median :53.98  
 Mean   : 12235961   Mean   :54.38  
 3rd Qu.: 13888152   3rd Qu.:60.10  
 Max.   :182201962   Max.   :77.60  
 NA's   :51                         </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(pop_lf.exp) <span class="co">#check the dimnensions of the data. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2907    2</code></pre>
</div>
</div>
</section>
<section id="plotting-data" class="level3">
<h3 class="anchored" data-anchor-id="plotting-data">Plotting data:</h3>
<p>Now we can start generating plots for the newly created variables. We will generate a scatterplot and plot life expecrtancy as a function of infant mortality.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>pt1 <span class="ot">&lt;-</span> inf.mort_lf.exp <span class="sc">%&gt;%</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(life_expectancy, infant_mortality)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">color =</span> <span class="st">"green"</span>,<span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figure 1. Life expectancy as a function of infant mortality"</span>)  <span class="co">#generate a scatterplot with regression line to demonstrate the positive or negative correlation. </span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pt1) <span class="co">#generate the scatterplot.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 226 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 226 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pt1) <span class="co">#print the plot. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 226 rows containing non-finite outside the scale range
(`stat_smooth()`).
Removed 226 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As shown in figure 1, there is a negative correlation between infant mortality and life expectancy.</p>
<p>Let’s generate another scatterplot by ploting population as a function of life expectancy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>pt2 <span class="ot">&lt;-</span> pop_lf.exp <span class="sc">%&gt;%</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(population, life_expectancy)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="fu">scale_x_log10</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figure 2. Population as a function of life expectancy"</span>) <span class="co">#generated a scatterplot with population on the x-axis and life_expectancy on the y-axis.Note: we have set x-axis to log scale. </span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pt2) <span class="co">#generate the plot.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 51 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 51 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pt2) <span class="co"># print the plot. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 51 rows containing non-finite outside the scale range
(`stat_smooth()`).
Removed 51 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As shown in figure 2, there a not very strong correlation between life expectancy and population. Note: x-axis is set to log scale.</p>
<p>Figure 2 shows individual streaks of data poits that go together. This is mainly because the data is collected over many years and each streak represents data from an individual year.</p>
</section>
<section id="more-data-processing" class="level3">
<h3 class="anchored" data-anchor-id="more-data-processing">More data processing:</h3>
<p>Determine the number of NA’s for infant moratlity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(africadata<span class="sc">$</span>infant_mortality) <span class="co">#look at the summary for NA's. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  11.40   62.20   93.40   95.12  124.70  237.40     226 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(africadata<span class="sc">$</span>infant_mortality)) <span class="co"># total number of NA's in infant mortality column.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 226</code></pre>
</div>
</div>
<p>Create another dataset called missing_df that only contains two variables, Year and infant mortlaity to further investigate the years that have missing data in the infant mortality column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>missing_df <span class="ot">&lt;-</span> africadata <span class="sc">%&gt;%</span> </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"year"</span>, <span class="st">"infant_mortality"</span>)  <span class="co">#variable called missing_df with the variables year and infant mortality.</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(missing_df, <span class="at">n =</span> <span class="dv">100</span> )  <span class="co">#view the first 100 rows of the newly created dataset.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    year infant_mortality
1   1960            148.2
2   1960            208.0
3   1960            186.9
4   1960            115.5
5   1960            161.3
6   1960            145.1
7   1960            166.9
8   1960               NA
9   1960            165.5
10  1960               NA
11  1960            200.0
12  1960            174.0
13  1960            110.6
14  1960            208.4
15  1960               NA
16  1960            209.6
17  1960               NA
18  1960               NA
19  1960            162.0
20  1960               NA
21  1960            148.4
22  1960            125.1
23  1960               NA
24  1960               NA
25  1960            118.6
26  1960            143.3
27  1960            212.0
28  1960            164.5
29  1960            112.0
30  1960            218.2
31  1960            237.4
32  1960            135.0
33  1960             67.8
34  1960            145.0
35  1960            183.0
36  1960            102.0
37  1960               NA
38  1960            165.0
39  1960            127.9
40  1960            126.3
41  1960             73.6
42  1960            223.6
43  1960               NA
44  1960            107.4
45  1960            141.7
46  1960            144.3
47  1960            162.4
48  1960            173.4
49  1960            132.3
50  1960            123.2
51  1960             92.6
52  1961            148.1
53  1961               NA
54  1961            183.9
55  1961            112.2
56  1961            159.4
57  1961            144.8
58  1961            163.3
59  1961               NA
60  1961            162.9
61  1961               NA
62  1961               NA
63  1961               NA
64  1961            108.4
65  1961            203.0
66  1961               NA
67  1961            202.7
68  1961               NA
69  1961               NA
70  1961               NA
71  1961               NA
72  1961            146.1
73  1961            123.8
74  1961            210.5
75  1961               NA
76  1961            114.0
77  1961            142.3
78  1961            212.1
79  1961            156.1
80  1961               NA
81  1961            216.4
82  1961            231.5
83  1961            131.9
84  1961             66.3
85  1961            142.7
86  1961               NA
87  1961               NA
88  1961               NA
89  1961               NA
90  1961            125.3
91  1961            126.0
92  1961             72.3
93  1961            220.5
94  1961               NA
95  1961            105.7
96  1961            140.1
97  1961            143.0
98  1961            159.4
99  1961            187.5
100 1961            129.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>missing_df <span class="ot">&lt;-</span> missing_df <span class="sc">%&gt;%</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(infant_mortality)) <span class="sc">%&gt;%</span>  <span class="co">#filter the NA's from infant mortality variable. </span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year) <span class="sc">%&gt;%</span>    <span class="co">#select the variable year that corresponds with the NA's in infant mortality column.</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()  <span class="co">#use it to avoid repetition of the same years. </span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(missing_df, <span class="at">n =</span> <span class="dv">100</span>)  <span class="co">#view the dataset.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   year
1  1960
2  1961
3  1962
4  1963
5  1964
6  1965
7  1966
8  1967
9  1968
10 1969
11 1970
12 1971
13 1972
14 1973
15 1974
16 1975
17 1976
18 1977
19 1978
20 1979
21 1980
22 1981
23 2016</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>year_2000 <span class="ot">&lt;-</span> africadata <span class="sc">%&gt;%</span>  <span class="co">#select the year 2000 from the year column to further investigate by generating plots. </span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2000</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(year_2000)  <span class="co">#get overview of the data structure.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   51 obs. of  9 variables:
 $ country         : Factor w/ 185 levels "Albania","Algeria",..: 2 3 18 22 26 27 29 31 32 33 ...
 $ year            : int  2000 2000 2000 2000 2000 2000 2000 2000 2000 2000 ...
 $ infant_mortality: num  33.9 128.3 89.3 52.4 96.2 ...
 $ life_expectancy : num  73.3 52.3 57.2 47.6 52.6 46.7 54.3 68.4 45.3 51.5 ...
 $ fertility       : num  2.51 6.84 5.98 3.41 6.59 7.06 5.62 3.7 5.45 7.35 ...
 $ population      : num  31183658 15058638 6949366 1736579 11607944 ...
 $ gdp             : num  5.48e+10 9.13e+09 2.25e+09 5.63e+09 2.61e+09 ...
 $ continent       : Factor w/ 5 levels "Africa","Americas",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ region          : Factor w/ 22 levels "Australia and New Zealand",..: 11 10 20 17 20 5 10 20 10 10 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(year_2000)  <span class="co">#summary of the dataset called year_2000 that has 51 observations and 9 variables. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         country        year      infant_mortality life_expectancy
 Algeria     : 1   Min.   :2000   Min.   : 12.30   Min.   :37.60  
 Angola      : 1   1st Qu.:2000   1st Qu.: 60.80   1st Qu.:51.75  
 Benin       : 1   Median :2000   Median : 80.30   Median :54.30  
 Botswana    : 1   Mean   :2000   Mean   : 78.93   Mean   :56.36  
 Burkina Faso: 1   3rd Qu.:2000   3rd Qu.:103.30   3rd Qu.:60.00  
 Burundi     : 1   Max.   :2000   Max.   :143.30   Max.   :75.00  
 (Other)     :45                                                  
   fertility       population             gdp               continent 
 Min.   :1.990   Min.   :    81154   Min.   :2.019e+08   Africa  :51  
 1st Qu.:4.150   1st Qu.:  2304687   1st Qu.:1.274e+09   Americas: 0  
 Median :5.550   Median :  8799165   Median :3.238e+09   Asia    : 0  
 Mean   :5.156   Mean   : 15659800   Mean   :1.155e+10   Europe  : 0  
 3rd Qu.:5.960   3rd Qu.: 17391242   3rd Qu.:8.654e+09   Oceania : 0  
 Max.   :7.730   Max.   :122876723   Max.   :1.329e+11                
                                                                      
                       region  
 Eastern Africa           :16  
 Western Africa           :16  
 Middle Africa            : 8  
 Northern Africa          : 6  
 Southern Africa          : 5  
 Australia and New Zealand: 0  
 (Other)                  : 0  </code></pre>
</div>
</div>
</section>
<section id="more-plotting" class="level3">
<h3 class="anchored" data-anchor-id="more-plotting">More plotting:</h3>
<p>We are going to generate scatterplots using the new dataset to further investigate it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>pt1.v2 <span class="ot">&lt;-</span> year_2000 <span class="sc">%&gt;%</span>       <span class="co">#generate a scatterplot of life_expectancy as a function of infant mortality which now holds data for the year 2000 only.</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(life_expectancy, infant_mortality)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">color =</span> <span class="st">"green"</span>, <span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figure 1a. Life expectancy as a function of infant mortality"</span>)  <span class="co">#generate scatterplot using this code with a few tweeks in the code to make the plot look better and more colorful. The labs argument is used to add custom titles to the scatterplot.</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pt1.v2) <span class="co">#generate the plot. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>pt2.v2 <span class="ot">&lt;-</span> year_2000 <span class="sc">%&gt;%</span>    <span class="co">#generate a scatterplot of population as a function of life expectancy which now holds data for the year 2000 only with 51 observations.</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(population, life_expectancy)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="fu">scale_x_log10</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figure 2a. Population as a function of life expectancy"</span>)   <span class="co">#generate scatterplot using this code with a few tweeks in the code to make the plot look better and more colorful. The argument labs is used to add custom titles to the scatterplot.</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pt2.v2)  <span class="co">#generate the plot.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="fitting-sample-models" class="level3">
<h3 class="anchored" data-anchor-id="fitting-sample-models">Fitting sample models:</h3>
<p>Fit a regession model for the two columns in the year_2000 dataset. The fit has life expectancy as an outcome and infant mortality as predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_expectancy <span class="sc">~</span> infant_mortality, <span class="at">data =</span> year_2000) <span class="co">#fit regression model with life expectancy as the outcome and infant mortality as predictor. Note: In the lm function, outcome lies on the left of tilde sign and predictor on the right side.  </span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1) <span class="co">#get the summary of the sample model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_expectancy ~ infant_mortality, data = year_2000)

Residuals:
     Min       1Q   Median       3Q      Max 
-22.6651  -3.7087   0.9914   4.0408   8.6817 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      71.29331    2.42611  29.386  &lt; 2e-16 ***
infant_mortality -0.18916    0.02869  -6.594 2.83e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.221 on 49 degrees of freedom
Multiple R-squared:  0.4701,    Adjusted R-squared:  0.4593 
F-statistic: 43.48 on 1 and 49 DF,  p-value: 2.826e-08</code></pre>
</div>
</div>
<p>Based on the p-value (p=2.83*10^-8), we conclude that there is strong evidence to reject the null hypothesis, which states that there is no relationship between infant mortality and life expectancy.This analysis shows a strong negative link between infant mortality and life expectancy in the year 2000. It means that for every extra infant death per 1,000 live births, life expectancy decreases by about 0.19 years (around 2.3 months).</p>
<p>Fit a regression model with life expectancy as outcome and population as predictor from the year_2000 dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_expectancy <span class="sc">~</span> population, <span class="at">data =</span> year_2000) <span class="co">#fit regession model with life expectancy as outcome and population as predictor.</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2) <span class="co">#get the summary for the fitted model.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_expectancy ~ population, data = year_2000)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.429  -4.602  -2.568   3.800  18.802 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 5.593e+01  1.468e+00  38.097   &lt;2e-16 ***
population  2.756e-08  5.459e-08   0.505    0.616    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.524 on 49 degrees of freedom
Multiple R-squared:  0.005176,  Adjusted R-squared:  -0.01513 
F-statistic: 0.2549 on 1 and 49 DF,  p-value: 0.6159</code></pre>
</div>
</div>
<p>In this model, based on the p-value (0.6159), the population variable does not have a significant effect on life expectancy. It’s likely not a meaningful predictor for life expectancy in this dataset.</p>
<p>```</p>
<section id="section" class="level73">
<p class="heading"></p>
</section>
</section>
<section id="this-section-was-contributed-to-by-shaun-van-den-hurk" class="level3">
<h3 class="anchored" data-anchor-id="this-section-was-contributed-to-by-shaun-van-den-hurk">This section was contributed to by Shaun van den Hurk</h3>
</section>
<section id="this-section-was-contributed-to-by-shaun-van-den-hurk-1" class="level3">
<h3 class="anchored" data-anchor-id="this-section-was-contributed-to-by-shaun-van-den-hurk-1">This section was contributed to by Shaun van den Hurk</h3>
<p>We will be working with another dataset from the dslabs package again. The different datasets that are available in the package can be seen online by viewing the details on CRAN. The website for the respective PDF with information on different datasets can be found here: https://cran.r-project.org/web/packages/dslabs/dslabs.pdf</p>
<p>load packages</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr) <span class="co"># For kable() table formatting</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)  <span class="co"># For data wrangling and plotting</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will work with a dataset that evaluates contagious disease data for US states.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Get an overview of the us_contagious_diseases data structure</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(us_contagious_diseases) <span class="co"># Understand the variables and types</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   16065 obs. of  6 variables:
 $ disease        : Factor w/ 7 levels "Hepatitis A",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ state          : Factor w/ 51 levels "Alabama","Alaska",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ year           : num  1966 1967 1968 1969 1970 ...
 $ weeks_reporting: num  50 49 52 49 51 51 45 45 45 46 ...
 $ count          : num  321 291 314 380 413 378 342 467 244 286 ...
 $ population     : num  3345787 3364130 3386068 3412450 3444165 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Get a summary of the us_contagious_diseases data</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(us_contagious_diseases) <span class="co"># Basic statistics across variables</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        disease            state            year      weeks_reporting
 Hepatitis A:2346   Alabama   :  315   Min.   :1928   Min.   : 0.00  
 Measles    :3825   Alaska    :  315   1st Qu.:1950   1st Qu.:31.00  
 Mumps      :1785   Arizona   :  315   Median :1975   Median :46.00  
 Pertussis  :2856   Arkansas  :  315   Mean   :1971   Mean   :37.38  
 Polio      :2091   California:  315   3rd Qu.:1990   3rd Qu.:50.00  
 Rubella    :1887   Colorado  :  315   Max.   :2011   Max.   :52.00  
 Smallpox   :1275   (Other)   :14175                                 
     count          population      
 Min.   :     0   Min.   :   86853  
 1st Qu.:     7   1st Qu.: 1018755  
 Median :    69   Median : 2749249  
 Mean   :  1492   Mean   : 4107584  
 3rd Qu.:   525   3rd Qu.: 4996229  
 Max.   :132342   Max.   :37607525  
                  NA's   :214       </code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Determine the object class for the us_contagious_diseases dataset</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(us_contagious_diseases) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#View the dataset help file information to learn more from documentation</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(us_contagious_diseases)</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a><span class="co">#View the dataset as a whole in the console</span></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(us_contagious_diseases)</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a><span class="co">#If not rendering you can print this too:</span></span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a><span class="co">#print(us_contagious_diseases)</span></span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Render friendly shorter view:</span></span>
<span id="cb85-11"><a href="#cb85-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(us_contagious_diseases, <span class="at">n =</span> <span class="dv">50</span>) <span class="co"># see the top 50 results printed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       disease   state year weeks_reporting count population
1  Hepatitis A Alabama 1966              50   321    3345787
2  Hepatitis A Alabama 1967              49   291    3364130
3  Hepatitis A Alabama 1968              52   314    3386068
4  Hepatitis A Alabama 1969              49   380    3412450
5  Hepatitis A Alabama 1970              51   413    3444165
6  Hepatitis A Alabama 1971              51   378    3481798
7  Hepatitis A Alabama 1972              45   342    3524543
8  Hepatitis A Alabama 1973              45   467    3571209
9  Hepatitis A Alabama 1974              45   244    3620548
10 Hepatitis A Alabama 1975              46   286    3671246
11 Hepatitis A Alabama 1976              50   220    3721914
12 Hepatitis A Alabama 1977              43   206    3771085
13 Hepatitis A Alabama 1978              41   203    3817217
14 Hepatitis A Alabama 1979              47   257    3858703
15 Hepatitis A Alabama 1980              37   200    3893888
16 Hepatitis A Alabama 1981              40   138    3921581
17 Hepatitis A Alabama 1982              43   128    3942588
18 Hepatitis A Alabama 1983              43   178    3958271
19 Hepatitis A Alabama 1984              35   115    3970041
20 Hepatitis A Alabama 1985              22    37    3979341
21 Hepatitis A Alabama 1986              26    51    3987637
22 Hepatitis A Alabama 1987              36    81    3996407
23 Hepatitis A Alabama 1988              20    13    4007144
24 Hepatitis A Alabama 1989              32    56    4021358
25 Hepatitis A Alabama 1990              41    86    4040587
26 Hepatitis A Alabama 1991              38    39    4066003
27 Hepatitis A Alabama 1992              34    35    4097169
28 Hepatitis A Alabama 1993              27    40    4133242
29 Hepatitis A Alabama 1994              29    72    4173361
30 Hepatitis A Alabama 1995              38    75    4216645
31 Hepatitis A Alabama 1996              44   196    4262177
32 Hepatitis A Alabama 1997              26    40    4309007
33 Hepatitis A Alabama 1998              34    64    4356137
34 Hepatitis A Alabama 1999              35    52    4402529
35 Hepatitis A Alabama 2000              42    53    4447100
36 Hepatitis A Alabama 2001              41    66    4488959
37 Hepatitis A Alabama 2002              47    35    4528129
38 Hepatitis A Alabama 2003              47    14    4564878
39 Hepatitis A Alabama 2004              41     6    4599490
40 Hepatitis A Alabama 2005              47    34    4632262
41 Hepatitis A Alabama 2006              42    17    4663504
42 Hepatitis A Alabama 2007              48    20    4693536
43 Hepatitis A Alabama 2008              49    10    4722691
44 Hepatitis A Alabama 2009              49    10    4751307
45 Hepatitis A Alabama 2010              51     8    4779736
46 Hepatitis A Alabama 2011              27     7    4808274
47 Hepatitis A  Alaska 1966              34    90     268476
48 Hepatitis A  Alaska 1967              22    39     276180
49 Hepatitis A  Alaska 1968              31    84     284068
50 Hepatitis A  Alaska 1969              32    63     292136</code></pre>
</div>
</div>
<p>We see that there are 16 065 variables and 6 observations,with the main columns being disease, state, year, weeks reporting,count, and population. We also see some of the diseases in the dataset and some of the associated figures. We see that the the minimum year in the dataset is 1928 and the maximum is 2011. Information is reported per week in the year and the total number where cases were reported gives the weeks reporting (from 0 to 52). The diseases investigated are: Hepatitis A, Measles, Mumps, Pertussis,Polio, Rubella, and Smallpox.</p>
<p>For our evaluations we will focus on a 20-year subset of the data: 1990 - 2010 which has good reporting of the data. We will filter this out of the main dataset and name the new object: us_illness_20y</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Focus analysis on the years 1990 to 2010</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>us_illness_20y <span class="ot">&lt;-</span> us_contagious_diseases <span class="sc">|&gt;</span> <span class="fu">filter</span>(year<span class="sc">&gt;</span><span class="dv">1989</span> <span class="sc">&amp;</span> year<span class="sc">&lt;</span><span class="dv">2011</span>) <span class="co">#Use the filter function to select for the rows that include the years 1990 - 2010</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="co">#View the reduced 20 Year dataset as a whole in the console although this will not display on the rendered website</span></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(us_illness_20y)</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a><span class="co">#If not rendering you can print this too:</span></span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a><span class="co">#print(us_illness_20y)</span></span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Render friendly shorter view:</span></span>
<span id="cb87-12"><a href="#cb87-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(us_illness_20y, <span class="at">n =</span> <span class="dv">50</span>) <span class="co"># see the top 50 results printed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       disease   state year weeks_reporting count population
1  Hepatitis A Alabama 1990              41    86    4040587
2  Hepatitis A Alabama 1991              38    39    4066003
3  Hepatitis A Alabama 1992              34    35    4097169
4  Hepatitis A Alabama 1993              27    40    4133242
5  Hepatitis A Alabama 1994              29    72    4173361
6  Hepatitis A Alabama 1995              38    75    4216645
7  Hepatitis A Alabama 1996              44   196    4262177
8  Hepatitis A Alabama 1997              26    40    4309007
9  Hepatitis A Alabama 1998              34    64    4356137
10 Hepatitis A Alabama 1999              35    52    4402529
11 Hepatitis A Alabama 2000              42    53    4447100
12 Hepatitis A Alabama 2001              41    66    4488959
13 Hepatitis A Alabama 2002              47    35    4528129
14 Hepatitis A Alabama 2003              47    14    4564878
15 Hepatitis A Alabama 2004              41     6    4599490
16 Hepatitis A Alabama 2005              47    34    4632262
17 Hepatitis A Alabama 2006              42    17    4663504
18 Hepatitis A Alabama 2007              48    20    4693536
19 Hepatitis A Alabama 2008              49    10    4722691
20 Hepatitis A Alabama 2009              49    10    4751307
21 Hepatitis A Alabama 2010              51     8    4779736
22 Hepatitis A  Alaska 1990              39   167     550043
23 Hepatitis A  Alaska 1991              37    80     561769
24 Hepatitis A  Alaska 1992              32    65     572122
25 Hepatitis A  Alaska 1993              24   374     581250
26 Hepatitis A  Alaska 1994              29   163     589317
27 Hepatitis A  Alaska 1995              39    38     596513
28 Hepatitis A  Alaska 1996              41    46     603039
29 Hepatitis A  Alaska 1997              24    20     609112
30 Hepatitis A  Alaska 1998              30     6     614959
31 Hepatitis A  Alaska 1999              36     7     620817
32 Hepatitis A  Alaska 2000              39     8     626932
33 Hepatitis A  Alaska 2001              40    10     633510
34 Hepatitis A  Alaska 2002              42    11     640570
35 Hepatitis A  Alaska 2003              44     8     648078
36 Hepatitis A  Alaska 2004              43     4     656003
37 Hepatitis A  Alaska 2005              44     3     664309
38 Hepatitis A  Alaska 2006               0     0     672961
39 Hepatitis A  Alaska 2007              42     3     681920
40 Hepatitis A  Alaska 2008              41     3     691147
41 Hepatitis A  Alaska 2009              46     6     700599
42 Hepatitis A  Alaska 2010              24     4     710231
43 Hepatitis A Arizona 1990              42  1645    3665228
44 Hepatitis A Arizona 1991              37   837    3783229
45 Hepatitis A Arizona 1992              35   761    3911122
46 Hepatitis A Arizona 1993              26   662    4047937
47 Hepatitis A Arizona 1994              29   934    4192532
48 Hepatitis A Arizona 1995              40   990    4343559
49 Hepatitis A Arizona 1996              43  1397    4499438
50 Hepatitis A Arizona 1997              27  1078    4658333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(us_illness_20y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        disease            state           year      weeks_reporting
 Hepatitis A:1071   Alabama   :  81   Min.   :1990   Min.   : 0.00  
 Measles    : 663   Alaska    :  81   1st Qu.:1994   1st Qu.:19.00  
 Mumps      : 663   Arizona   :  81   Median :1998   Median :38.00  
 Pertussis  :1071   Arkansas  :  81   Mean   :1998   Mean   :30.67  
 Polio      :   0   California:  81   3rd Qu.:2002   3rd Qu.:45.00  
 Rubella    : 663   Colorado  :  81   Max.   :2010   Max.   :52.00  
 Smallpox   :   0   (Other)   :3645                                 
     count          population      
 Min.   :   0.0   Min.   :  452414  
 1st Qu.:   1.0   1st Qu.: 1326846  
 Median :  14.0   Median : 3685296  
 Mean   : 104.1   Mean   : 5377467  
 3rd Qu.:  77.0   3rd Qu.: 6283172  
 Max.   :9598.0   Max.   :37253956  
                                    </code></pre>
</div>
</div>
<p>From this filtered dataset covering 1990 to 2010:</p>
<ul>
<li>Hepatitis A and Pertussis have the highest number of records, suggesting they were more frequently reported or monitored during this period.</li>
<li>Polio and Smallpox have zero entries, consistent with their elimination or near-elimination in the U.S. by the 1990s.</li>
<li>The range in population sizes (from under 500,000 to over 37 million) reinforces why it’s important to normalize case counts by population.</li>
<li>The variable weeks_reporting shows variation, which could reflect differences in surveillance intensity across states or diseases.</li>
</ul>
<p>We want to look if there are any missing (na) values in our selected dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for any NAs</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>us_illness_20y <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">if_any</span>(<span class="fu">everything</span>(), is.na)) <span class="co">#Filter used, If_any helps to check all columns, and everything applies the is.na function to all the columns.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] disease         state           year            weeks_reporting
[5] count           population     
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
<p>We see that there are no NA values in the dataset and so we do not need to do further data cleaning to address any NA values.</p>
<p>Having confirmed the structure and completeness of our 20-year subset, we can now move forward with: - Evaluating trends in selected diseases (e.g., measles, hepatitis A) - Comparing states and years by total case numbers - Normalizing case counts by population to uncover relative disease burden</p>
</section>
<section id="further-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="further-data-analysis">Further data analysis:</h3>
<p>Since we identified it as one of the diseases with highest reported incidence, we would like to know how many cases of Hepatitis A there were in 2010 across all States.We will name the result as an assigned object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co">#First we will create an object with all the Hepatitis A cases in 2010 filtered </span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>hepatitis_A_2010 <span class="ot">&lt;-</span> us_contagious_diseases <span class="sc">|&gt;</span><span class="fu">filter</span>(disease<span class="sc">==</span><span class="st">'Hepatitis A'</span> <span class="sc">&amp;</span> year<span class="sc">==</span><span class="dv">2010</span>) </span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="co">#We will now get a sum of all the case counts from the hepatitis cases in 2010</span></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Total case count for Hepatitis A in 2010</span></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>hep_A_2010_count <span class="ot">&lt;-</span> <span class="fu">sum</span>(hepatitis_A_2010 <span class="sc">$</span>count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We see that there were 4060 cases of Hepatitis A in 2010. We can view our intermediate object that was created “hepatitis_A_2010” and visually see that New York was the State with the highest number of cases. Of course we could generate code to filter and evaluate this further too.</p>
<p>The code from above can be edited and used to evaluate any other disease and year combination present in the dataset (e.g.&nbsp;Measles and Georgia).</p>
<p>We want to visually see/confirm which state had the highest number of Hepatitis A cases in 2010.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Generate a bar chart that displays Hepatitis A case numbers by state from the year 2010</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> hepatitis_A_2010, <span class="fu">aes</span>(<span class="at">x =</span>state, <span class="at">y =</span>count)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Hepatitis A cases by State in 2010"</span>, <span class="at">x =</span> <span class="st">"States"</span>, <span class="at">y =</span> <span class="st">"Hepatitis cases"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Use the ggplot function with aes and define the variables, define a bar chart by using geom_bar, add labels with labs, and then specify that the x-axis labels rotate 90 degrees by using the theme function.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We confirm that New York State had the highest number of Hepatitis A cases in 2010.</p>
<p>We would then like to see which year had the highest number of cases of Measles.</p>
<p>We will first filter out the Measles cases and create an object from the filtered cases. We will then get the total number of cases from all the states per year. This will then be used to give us the year with the highest number of cases.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Use the filter function and view the results</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter dataset for measles cases in the 20-year window</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>measles_cases <span class="ot">&lt;-</span> us_illness_20y<span class="sc">|&gt;</span> <span class="fu">filter</span>(disease<span class="sc">==</span><span class="st">'Measles'</span>)</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(measles_cases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        disease           state          year      weeks_reporting
 Hepatitis A:  0   Alabama   : 13   Min.   :1990   Min.   : 0.00  
 Measles    :663   Alaska    : 13   1st Qu.:1993   1st Qu.: 0.00  
 Mumps      :  0   Arizona   : 13   Median :1996   Median :14.00  
 Pertussis  :  0   Arkansas  : 13   Mean   :1996   Mean   :17.53  
 Polio      :  0   California: 13   3rd Qu.:1999   3rd Qu.:36.00  
 Rubella    :  0   Colorado  : 13   Max.   :2002   Max.   :51.00  
 Smallpox   :  0   (Other)   :585                                 
     count           population      
 Min.   :   0.00   Min.   :  452414  
 1st Qu.:   0.00   1st Qu.: 1277190  
 Median :   1.00   Median : 3571367  
 Mean   :  51.39   Mean   : 5254431  
 3rd Qu.:   7.00   3rd Qu.: 6148264  
 Max.   :9598.00   Max.   :34529758  
                                     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Render friendly approach to viewing the data although this will not display on the rendered website</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(measles_cases, <span class="at">n =</span> <span class="dv">50</span>) <span class="co"># see the top 50 results printed (a little over two of the 20 year periods)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   disease    state year weeks_reporting count population
1  Measles  Alabama 1990              39    28    4040587
2  Measles  Alabama 1991              10     1    4066003
3  Measles  Alabama 1992               0     0    4097169
4  Measles  Alabama 1993              30     1    4133242
5  Measles  Alabama 1994               0     0    4173361
6  Measles  Alabama 1995               0     0    4216645
7  Measles  Alabama 1996               0     0    4262177
8  Measles  Alabama 1997               1     6    4309007
9  Measles  Alabama 1998              17     0    4356137
10 Measles  Alabama 1999               0     0    4402529
11 Measles  Alabama 2000               0     0    4447100
12 Measles  Alabama 2001               0     0    4488959
13 Measles  Alabama 2002               5     7    4528129
14 Measles   Alaska 1990              39    27     550043
15 Measles   Alaska 1991              12     1     561769
16 Measles   Alaska 1992              40     4     572122
17 Measles   Alaska 1993               0     0     581250
18 Measles   Alaska 1994              26    16     589317
19 Measles   Alaska 1995               0     0     596513
20 Measles   Alaska 1996              43    68     603039
21 Measles   Alaska 1997               1     1     609112
22 Measles   Alaska 1998              16    16     614959
23 Measles   Alaska 1999               0     0     620817
24 Measles   Alaska 2000              32     1     626932
25 Measles   Alaska 2001               0     0     633510
26 Measles   Alaska 2002               0     0     640570
27 Measles  Arizona 1990              45   285    3665228
28 Measles  Arizona 1991              47   342    3783229
29 Measles  Arizona 1992              18     0    3911122
30 Measles  Arizona 1993              22     3    4047937
31 Measles  Arizona 1994              20     9    4192532
32 Measles  Arizona 1995              47    12    4343559
33 Measles  Arizona 1996              36     8    4499438
34 Measles  Arizona 1997              36     9    4658333
35 Measles  Arizona 1998               9    10    4818136
36 Measles  Arizona 1999              30     1    4976457
37 Measles  Arizona 2000               0     0    5130632
38 Measles  Arizona 2001              14     1    5278300
39 Measles  Arizona 2002               0     0    5419266
40 Measles Arkansas 1990              31    41    2350725
41 Measles Arkansas 1991               0     0    2368201
42 Measles Arkansas 1992               0     0    2391223
43 Measles Arkansas 1993               0     0    2418991
44 Measles Arkansas 1994               0     0    2450696
45 Measles Arkansas 1995              42     2    2485501
46 Measles Arkansas 1996               0     0    2522529
47 Measles Arkansas 1997               1     3    2560848
48 Measles Arkansas 1998               0     0    2599475
49 Measles Arkansas 1999               9     4    2637361
50 Measles Arkansas 2000               7     1    2673400</code></pre>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(measles_cases)</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a><span class="co">#If not rendering you can print this too but the list will have 663 rows:</span></span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a><span class="co">#print(measles_cases)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note: Although the summary() output still listed other diseases (e.g., Mumps), this is due to how R handles categorical variables (factors). The filter operation worked correctly — the dataset contains only Measles cases.</p>
<p>From this evaluation we can see that our dataset for the reported measles cases ends in 2002 and not 2010 (or 2011) like the other diseases in the reported dataset. So our period of evaluation for measles is 1990 to 2002.</p>
<p>From our summary we also see that the max value in the “count” column is 9598, and we could use this to query the state and year with the highest case if we wanted. But we want the highest number of total cases per year and so will continue with that workflow.</p>
<p>We first want to see which states were actually included in the dataset. We will use the unique function from the dplyr package to identify these.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get list of unique states</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(measles_cases<span class="sc">$</span>state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Alabama              Alaska               Arizona             
 [4] Arkansas             California           Colorado            
 [7] Connecticut          Delaware             District Of Columbia
[10] Florida              Georgia              Hawaii              
[13] Idaho                Illinois             Indiana             
[16] Iowa                 Kansas               Kentucky            
[19] Louisiana            Maine                Maryland            
[22] Massachusetts        Michigan             Minnesota           
[25] Mississippi          Missouri             Montana             
[28] Nebraska             Nevada               New Hampshire       
[31] New Jersey           New Mexico           New York            
[34] North Carolina       North Dakota         Ohio                
[37] Oklahoma             Oregon               Pennsylvania        
[40] Rhode Island         South Carolina       South Dakota        
[43] Tennessee            Texas                Utah                
[46] Vermont              Virginia             Washington          
[49] West Virginia        Wisconsin            Wyoming             
51 Levels: Alabama Alaska Arizona Arkansas California Colorado ... Wyoming</code></pre>
</div>
</div>
<p>We can see that 51 States are included in the dataset.</p>
<p>We will continue with our process to see the total number of measles cases by year.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We get the total measles cases by grouping the years together and then using the sum function on the count and then summarise these results</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize measles totals per year</span></span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>measles_total_cases <span class="ot">&lt;-</span> measles_cases <span class="sc">|&gt;</span> <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">total_cases=</span><span class="fu">sum</span>(count))</span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(measles_total_cases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 2
    year total_cases
   &lt;dbl&gt;       &lt;dbl&gt;
 1  1990       21734
 2  1991        8122
 3  1992        1840
 4  1993         213
 5  1994         689
 6  1995         212
 7  1996         465
 8  1997         533
 9  1998          58
10  1999          61
11  2000          56
12  2001          73
13  2002          14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show summary of annual case totals</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(measles_total_cases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      year       total_cases   
 Min.   :1990   Min.   :   14  
 1st Qu.:1993   1st Qu.:   61  
 Median :1996   Median :  213  
 Mean   :1996   Mean   : 2621  
 3rd Qu.:1999   3rd Qu.:  689  
 Max.   :2002   Max.   :21734  </code></pre>
</div>
</div>
<p>Through the print and summary functions we can see that the year with the highest total number of measles cases was 2002, when there were 21734 cases of measles across all states.</p>
<p>We can display the total measles cases as a line graph to help visualise any patterns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co">#First we want to make sure that years are seen as a factor/categorical for the plot.</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>measles_total_cases<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(measles_total_cases<span class="sc">$</span>year)</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot a line graph with the appropriate variables and labels. Ensure that we have group set as 1 since this is a line plot with factors.</span></span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> measles_total_cases, <span class="fu">aes</span>(<span class="at">x=</span>year, <span class="at">y=</span> total_cases)) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">group=</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title=</span> <span class="st">"Total measles cases for all US states by year"</span>, <span class="at">x =</span> <span class="st">"year"</span>, <span class="at">y =</span> <span class="st">"Total cases"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The graph that we plotted helps to illustrate a decreasing trend in the number of cases of measles at the start of the 1990s. By the late 1990s and early 2000s, case counts sharply decreased, this could suggest improvements in vaccination coverage and public health response. If we wanted to evaluate this further we could go back to the original dataset and plot the measles cases over a longer time frame.</p>
<p>The same work flow and code can be used and adjusted for different diseases and time frames.</p>
<p>We now acknowledge that raw case numbers might be limited due to differences in population sizes. For example, New York has a much greater population, and so instead we want to compare the percentage of the population affected (number of cases per the population *100) which will give us a comparable metric.</p>
<p>We will calculate the percent of the population affected and add this as an additional column to the measles dataset. We will then order the dataset by the percent affected column to see this visually.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column that calculates the percent of the population affected by measles</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This helps normalize across states with large and small populations</span></span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (e.g., 1,000 cases in New York vs. 1,000 in Vermont are not equivalent in population impact)</span></span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a><span class="co">#adding an additonal column with the mutate function</span></span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>measles_percent <span class="ot">&lt;-</span> measles_cases<span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">percent_affected =</span> count<span class="sc">/</span>population<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb108-7"><a href="#cb108-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-8"><a href="#cb108-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Reorder the percent of the population affected from highest to lowest</span></span>
<span id="cb108-9"><a href="#cb108-9" aria-hidden="true" tabindex="-1"></a>measles_percent_top <span class="ot">&lt;-</span> measles_percent <span class="sc">|&gt;</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(percent_affected))</span>
<span id="cb108-10"><a href="#cb108-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-11"><a href="#cb108-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Render friendly approach to viewing the data although this will not display on the rendered website</span></span>
<span id="cb108-12"><a href="#cb108-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(measles_cases, <span class="at">n =</span> <span class="dv">50</span>) <span class="co"># see the top 50 results printed (a little over four of the 12 year periods - data from just over four states)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   disease    state year weeks_reporting count population
1  Measles  Alabama 1990              39    28    4040587
2  Measles  Alabama 1991              10     1    4066003
3  Measles  Alabama 1992               0     0    4097169
4  Measles  Alabama 1993              30     1    4133242
5  Measles  Alabama 1994               0     0    4173361
6  Measles  Alabama 1995               0     0    4216645
7  Measles  Alabama 1996               0     0    4262177
8  Measles  Alabama 1997               1     6    4309007
9  Measles  Alabama 1998              17     0    4356137
10 Measles  Alabama 1999               0     0    4402529
11 Measles  Alabama 2000               0     0    4447100
12 Measles  Alabama 2001               0     0    4488959
13 Measles  Alabama 2002               5     7    4528129
14 Measles   Alaska 1990              39    27     550043
15 Measles   Alaska 1991              12     1     561769
16 Measles   Alaska 1992              40     4     572122
17 Measles   Alaska 1993               0     0     581250
18 Measles   Alaska 1994              26    16     589317
19 Measles   Alaska 1995               0     0     596513
20 Measles   Alaska 1996              43    68     603039
21 Measles   Alaska 1997               1     1     609112
22 Measles   Alaska 1998              16    16     614959
23 Measles   Alaska 1999               0     0     620817
24 Measles   Alaska 2000              32     1     626932
25 Measles   Alaska 2001               0     0     633510
26 Measles   Alaska 2002               0     0     640570
27 Measles  Arizona 1990              45   285    3665228
28 Measles  Arizona 1991              47   342    3783229
29 Measles  Arizona 1992              18     0    3911122
30 Measles  Arizona 1993              22     3    4047937
31 Measles  Arizona 1994              20     9    4192532
32 Measles  Arizona 1995              47    12    4343559
33 Measles  Arizona 1996              36     8    4499438
34 Measles  Arizona 1997              36     9    4658333
35 Measles  Arizona 1998               9    10    4818136
36 Measles  Arizona 1999              30     1    4976457
37 Measles  Arizona 2000               0     0    5130632
38 Measles  Arizona 2001              14     1    5278300
39 Measles  Arizona 2002               0     0    5419266
40 Measles Arkansas 1990              31    41    2350725
41 Measles Arkansas 1991               0     0    2368201
42 Measles Arkansas 1992               0     0    2391223
43 Measles Arkansas 1993               0     0    2418991
44 Measles Arkansas 1994               0     0    2450696
45 Measles Arkansas 1995              42     2    2485501
46 Measles Arkansas 1996               0     0    2522529
47 Measles Arkansas 1997               1     3    2560848
48 Measles Arkansas 1998               0     0    2599475
49 Measles Arkansas 1999               9     4    2637361
50 Measles Arkansas 2000               7     1    2673400</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(measles_cases)</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="co">#If not rendering you can print this too but the list will have 663 rows:</span></span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a><span class="co">#print(measles_percent_top)</span></span>
<span id="cb110-5"><a href="#cb110-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-6"><a href="#cb110-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Display top 10 state-year combinations using kable for clean output</span></span>
<span id="cb110-7"><a href="#cb110-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(measles_percent_top, <span class="dv">10</span>), <span class="at">caption =</span> <span class="st">"Top 10 State-Year Combinations by Measles Percent Affected"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 10 State-Year Combinations by Measles Percent Affected</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 6%">
<col style="width: 21%">
<col style="width: 7%">
<col style="width: 14%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">disease</th>
<th style="text-align: left;">state</th>
<th style="text-align: right;">year</th>
<th style="text-align: right;">weeks_reporting</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">population</th>
<th style="text-align: right;">percent_affected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Measles</td>
<td style="text-align: left;">Idaho</td>
<td style="text-align: right;">1991</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">439</td>
<td style="text-align: right;">1021923</td>
<td style="text-align: right;">0.0429582</td>
</tr>
<tr class="even">
<td style="text-align: left;">Measles</td>
<td style="text-align: left;">California</td>
<td style="text-align: right;">1990</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">9598</td>
<td style="text-align: right;">29760021</td>
<td style="text-align: right;">0.0322513</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Measles</td>
<td style="text-align: left;">Texas</td>
<td style="text-align: right;">1990</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">3898</td>
<td style="text-align: right;">16986510</td>
<td style="text-align: right;">0.0229476</td>
</tr>
<tr class="even">
<td style="text-align: left;">Measles</td>
<td style="text-align: left;">Nevada</td>
<td style="text-align: right;">1990</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">216</td>
<td style="text-align: right;">1201833</td>
<td style="text-align: right;">0.0179725</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Measles</td>
<td style="text-align: left;">Wisconsin</td>
<td style="text-align: right;">1990</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">657</td>
<td style="text-align: right;">4891769</td>
<td style="text-align: right;">0.0134307</td>
</tr>
<tr class="even">
<td style="text-align: left;">Measles</td>
<td style="text-align: left;">New Jersey</td>
<td style="text-align: right;">1991</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">1019</td>
<td style="text-align: right;">7793388</td>
<td style="text-align: right;">0.0130752</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Measles</td>
<td style="text-align: left;">Utah</td>
<td style="text-align: right;">1991</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">1758275</td>
<td style="text-align: right;">0.0125123</td>
</tr>
<tr class="even">
<td style="text-align: left;">Measles</td>
<td style="text-align: left;">Pennsylvania</td>
<td style="text-align: right;">1991</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">1402</td>
<td style="text-align: right;">11905415</td>
<td style="text-align: right;">0.0117762</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Measles</td>
<td style="text-align: left;">Alaska</td>
<td style="text-align: right;">1996</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">603039</td>
<td style="text-align: right;">0.0112762</td>
</tr>
<tr class="even">
<td style="text-align: left;">Measles</td>
<td style="text-align: left;">Vermont</td>
<td style="text-align: right;">1997</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">597142</td>
<td style="text-align: right;">0.0098804</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From this we can see that Idaho in 1991 had the highest value for percent of the population affected by measles. This was followed by California, Texas, Nevada and the Wisconsin, all in 1990. This supports the earlier observation that measles cases peaked in the early part of the study window.</p>
<p>Percent of Population Affected by Measles Over Time (Top 5 States) While we’ve looked at total case counts and peak values, it’s also helpful to see how measles impacted the population over time in the states most affected. This plot shows the percent of population affected by year for the five states with the highest average impact.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify top 5 states by average measles percent affected across all years</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>top_states <span class="ot">&lt;-</span> measles_percent <span class="sc">|&gt;</span></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state) <span class="sc">|&gt;</span></span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_percent =</span> <span class="fu">mean</span>(percent_affected)) <span class="sc">|&gt;</span></span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(avg_percent, <span class="at">n =</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(state)</span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-8"><a href="#cb111-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter original dataset to include only these top states</span></span>
<span id="cb111-9"><a href="#cb111-9" aria-hidden="true" tabindex="-1"></a>measles_top_states <span class="ot">&lt;-</span> measles_percent <span class="sc">|&gt;</span></span>
<span id="cb111-10"><a href="#cb111-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">%in%</span> top_states)</span>
<span id="cb111-11"><a href="#cb111-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-12"><a href="#cb111-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert year to a factor so x-axis shows as categorical integers</span></span>
<span id="cb111-13"><a href="#cb111-13" aria-hidden="true" tabindex="-1"></a>measles_top_states<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(measles_top_states<span class="sc">$</span>year)</span>
<span id="cb111-14"><a href="#cb111-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-15"><a href="#cb111-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot percent of population affected over time for these top states</span></span>
<span id="cb111-16"><a href="#cb111-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(measles_top_states, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> percent_affected, <span class="at">color =</span> state, <span class="at">group =</span> state)) <span class="sc">+</span></span>
<span id="cb111-17"><a href="#cb111-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb111-18"><a href="#cb111-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb111-19"><a href="#cb111-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Measles Impact Over Time</span><span class="sc">\n</span><span class="st">Top 5 States by % of Population Affected"</span>,</span>
<span id="cb111-20"><a href="#cb111-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb111-21"><a href="#cb111-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"% of Population Affected"</span></span>
<span id="cb111-22"><a href="#cb111-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb111-23"><a href="#cb111-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb111-24"><a href="#cb111-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb111-25"><a href="#cb111-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb111-26"><a href="#cb111-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot shows that the states with the highest measles burden relative to population size —including Idaho, California, Texas, Utah, and Alaska—experienced their peaks almost entirely between 1990 and 1992. In particular, Idaho had a spike exceeding 4% of its population affected in a single year.</p>
<p>By 1993, these values dropped sharply across all top states and remained close to zero thereafter. This trend is consistent with the national measles elimination effort in the U.S. during the early 1990s, suggesting strong vaccine rollout and public health interventions led to rapid containment.</p>
<p>These results reinforce our earlier conclusion: while absolute case counts can highlight outbreaks, percent-based metrics are essential for understanding true population impact, especially in smaller states like Idaho.</p>
<p>We will now run a basic linear regression model to investigate if there is any correlation between the percent of the population that is affected and the population size.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a linear model to explore relationship between population size and the percent of the population affected by measles</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 'lm' fits a linear regression model</span></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 'percent_affected' is the dependent (response) variable</span></span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 'population' is the independent (predictor) variable</span></span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a><span class="co">#generate a linear model with the highlighted variables</span></span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>measles_cases_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(percent_affected <span class="sc">~</span> population, <span class="at">data =</span> measles_percent)</span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-8"><a href="#cb113-8" aria-hidden="true" tabindex="-1"></a><span class="co">#display the results of the linear model</span></span>
<span id="cb113-9"><a href="#cb113-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(measles_cases_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = percent_affected ~ population, data = measles_percent)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.001793 -0.000743 -0.000622 -0.000516  0.042363 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 5.584e-04  1.528e-04   3.655 0.000277 ***
population  3.575e-11  1.946e-11   1.838 0.066556 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.002923 on 661 degrees of freedom
Multiple R-squared:  0.005083,  Adjusted R-squared:  0.003578 
F-statistic: 3.377 on 1 and 661 DF,  p-value: 0.06656</code></pre>
</div>
</div>
<p>The intercept estimate is 0.0005584, and the population coefficient is 3.575e-11. The p-value for population is 0.067, which is just above the conventional threshold for significance (0.05), indicating a marginal association. The R² value is only 0.005, indicating that population size explains less than 1% of the variance in measles percent affected. Residual errors are small but skewed slightly, and the F-test is not strongly significant.</p>
<p>Based on these results it appears that there is not a statistically significant relationship between the the percent of the population affected by measles and the population size. This suggests that population alone is not a useful predictor for the impact of measles, and additional factors (e.g., vaccination coverage, urbanization, reporting practices) would need to be considered in further analyses.</p>
<p>Although perhaps this could be evaluated over a longer time frame since the bulk of the cases occured within the first few years of 1990s within our filtered dataset.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>